export const GET_DATA_START = "GET_DATA_START";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const GET_STORY_START = "GET_STORY_START";
export const GET_STORY_SUCCESS = "GET_STORY_SUCCESS";
export const GET_STORY_FAILURE = "GET_STORY_FAILURE";

export const GET_COMMENTS_START = "GET_COMMENTS_START";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE";

export const ADD_POST_START = "ADD_POST_START";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const REJECT_STORY_START = "REJECT_STORY_START";
export const REJECT_STORY_SUCCESS = "REJECT_STORY_SUCCESS";
export const REJECT_STORY_FAILURE = "REJECT_STORY_FAILURE";

export const ACCEPT_STORIES_START = "ACCEPT_STORIES_START";
export const ACCEPT_STORIES_SUCCESS = "ACCEPT_STORIES_SUCCESS";
export const ACCEPT_STORIES_FAILURE = "ACCEPT_STORIES_FAILURE";

export const APPROVED_STORIES_START = "APPROVED_STORIES_START";
export const APPROVED_STORIES_SUCCESS = "APPROVED_STORIES_SUCCESS";
export const APPROVED_STORIES_FAILURE = "APPROVED_STORIES_FAILURE";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const DELETE_STORY_START = "DELETE_STORY_START"
export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS"
export const DELETE_STORY_FAILURE = "DELETE_STORY_FAILURE"
